### ISSUE TITLE
unit tests fail

### ISSUE THREAD

**Issue by davidpeterunderhill** [flnaves/airplane#4]
Node: 6a4ca8c8f28a, Instance: IRIS

USER>set ^UnitTestRoot="/opt/irisapp/tests/UnitTest/Report"

USER>do ##class(%UnitTest.Manager).RunTest(,"/nodelete")

===============================================================================
Directory: /opt/irisapp/tests/UnitTest/Report/
===============================================================================
  (root) begins ...
Load of directory started on 02/26/2021 17:21:13 '*.xml;*.XML;*.cls;*.mac;*.int;*.inc;*.CLS;*.MAC;*.INT;*.INC'

Loading file /opt/irisapp/tests/UnitTest/Report/WebREST.cls as udl

Compilation started on 02/26/2021 17:21:13 with qualifiers '/nodelete', using worker jobs
Compiling class UnitTest.Report.WebREST
Compiling routine UnitTest.Report.WebREST.1
Compilation finished successfully in 0.154s.

Load finished successfully.

    UnitTest.Report.WebREST begins ...
      TestGetAllCategoryInfo() begins ...{"Result":[
LogStateStatus:0:TestGetAllCategoryInfo: ERROR #5002: ObjectScript error: <UNDEFINED>zGetAllCategoryInfo+12^dc.Report.WebREST.1 *category  <<==== **FAILED**   (root):UnitTest.Report.WebREST:TestGetAllCategoryInfo      
      TestGetAllCategoryInfo failed
      TestGetAllTypeInfo() begins ...{"Result":[
LogStateStatus:0:TestGetAllTypeInfo: ERROR #5002: ObjectScript error: <UNDEFINED>zGetAllTypeInfo+15^dc.Report.WebREST.1 *type  <<==== **FAILED**   (root):UnitTest.Report.WebREST:TestGetAllTypeInfo
      TestGetAllTypeInfo failed
      TestGetGeographicInformationLevelNumber() begins ...{"Result":[]}
        AssertStatusOK:Getting all geographic level number information (passed)
        LogMessage:Duration of execution: .000088 sec.
      TestGetGeographicInformationLevelNumber passed
    UnitTest.Report.WebREST failed
  Skipping deleting classes
  (root) failed

Use the following URL to view the result:
http://172.18.0.2:52773/csp/sys/%25UnitTest.Portal.Indices.cls?Index=1&$NAMESPACE=USER
Some tests FAILED in suites:

**Comment by flnaves** [comment]
Hello David,  we are finishing the Project to Grand Prix Contest, so until 28 February we will do some corrections, thanks for your email. Best Regards,Flávio.   De: davidpeterunderhillEnviado:sexta-feira, 26 de fevereiro de 2021 14:24Para: flnaves/airplaneCc:SubscribedAssunto: [flnaves/airplane] unit tests fail (#4) Node: 6a4ca8c8f28a, Instance: IRISUSER>set ^UnitTestRoot="/opt/irisapp/tests/UnitTest/Report"USER>do ##class(%UnitTest.Manager).RunTest(,"/nodelete")===============================================================================Directory: /opt/irisapp/tests/UnitTest/Report/(root) begins ...Load of directory started on 02/26/2021 17:21:13 '.xml;.XML;.cls;.mac;.int;.inc;.CLS;.MAC;.INT;.INC'Loading file /opt/irisapp/tests/UnitTest/Report/WebREST.cls as udlCompilation started on 02/26/2021 17:21:13 with qualifiers '/nodelete', using worker jobsCompiling class UnitTest.Report.WebRESTCompiling routine UnitTest.Report.WebREST.1Compilation finished successfully in 0.154s.Load finished successfully.UnitTest.Report.WebREST begins ...  TestGetAllCategoryInfo() begins ...{"Result":[LogStateStatus:0:TestGetAllCategoryInfo: ERROR #5002: ObjectScript error: zGetAllCategoryInfo+12^dc.Report.WebREST.1 *category <<==== FAILED (root):UnitTest.Report.WebREST:TestGetAllCategoryInfoTestGetAllCategoryInfo failedTestGetAllTypeInfo() begins ...{"Result":[LogStateStatus:0:TestGetAllTypeInfo: ERROR #5002: ObjectScript error: zGetAllTypeInfo+15^dc.Report.WebREST.1 *type <<==== FAILED (root):UnitTest.Report.WebREST:TestGetAllTypeInfoTestGetAllTypeInfo failedTestGetGeographicInformationLevelNumber() begins ...{"Result":[]}AssertStatusOK:Getting all geographic level number information (passed)LogMessage:Duration of execution: .000088 sec.TestGetGeographicInformationLevelNumber passedUnitTest.Report.WebREST failedSkipping deleting classes(root) failedUse the following URL to view the result:http://172.18.0.2:52773/csp/sys/%25UnitTest.Portal.Indices.cls?Index=1&$NAMESPACE=USERSome tests FAILED in suites:—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
